server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kakaopay
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql
  data:
    web:
      pageable:
        default-page-size: 10
  h2:
    console:
      enabled: true
logging:
  level:
    com.kakaopay.throwmoney : debug
    org:
      springframework:
        web: debug
        jdbc: debug
#        transaction: trace
      hibernate:
        SQL: debug
        type:
          BasicTypeRegistry: off
